#:schema node_modules/wrangler/config-schema.json
name = "workersublink"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "40c578958de24784b410973563f0c590" }
]

[assets]
directory = "./public"
